using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class ShowValue : MonoBehaviour
{
    //“_”‚ğŠi”[‚·‚é•Ï”
    public int value = 0;
    public int type = 0;

    public Text text; 

    // Use this for initialization
    void Start()
    {

    }

    // Update is called once per frame
    void Update()
    {
        //RD
        if(type == 0)
        {
            value = CardBoardManager._MountainCardNum;
            GetComponent<Text>().text = "RD  :" + value.ToString() + "–‡";
        }
        //èD
        if (type == 1)
        {
            value = CardBoardManager._HandCardNum;
            GetComponent<Text>().text = "èD  :" + value.ToString() + "–‡";
        }
        //Ì‚ÄD
        if (type == 2)
        {
            value = CardBoardManager._GabageCardNum;
            GetComponent<Text>().text = "Ì‚ÄD:" + value.ToString() + "–‡";
        }
    }
}
